### ISSUE TITLE
Virtual Host

### ISSUE THREAD

**Issue by ssvaidyanathan** [anil614sagar/openapi2apigee#20]
If we try to pass a custom or one of the default virtual host, it tries to deploy on the defaulted values as well

For example

API name: Utility bill API, Version: 1.0.0
Apigee API bundle generated in location /Users/saisaranvaidyanathan/Desktop
Initiating Apigee Deployment..
? Base URI? https://api.enterprise.apigee.com
? Organization? apigee-cs
? User Id? ssvaidyanathan@apigee.com
? Password? *************
? Environment? test
? Virtual Hosts? default
[Error: Invalid virtual host reference secure. Context Revision:1;APIProxy:ExtAPI;Organization:apigee-cs;Environment:test]

I do not want to "secure" Virtual host, but it still tries to reference "secure"

**Comment by orangewise** [comment]
Hi @ssvaidyanathan, I think this is already solved by this commit:

https://github.com/anil614sagar/openapi2apigee/commit/577ad6cea7d02c64745678cf70e81025702d4b40
