### ISSUE TITLE
travis

### ISSUE THREAD

**Issue by orangewise** [anil614sagar/openapi2apigee#21]
Hi Anil, would it be an idea to move this repo into its own organisation? I would like to add travis-ci integration which I currently cannot do. Please let me know your thoughts.

**Comment by anil614sagar** [comment]
+1 @orangewise  , Great feature to have,

Seems like i just need to enable same to make it work with current org. Please see thread [here](http://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator)

I have done same, You can able to integrate same now. Keep me posted if you see any issues.

**Comment by orangewise** [comment]
Cool, it seems to be working :) Thanks!

**Comment by anil614sagar** [comment]
Thank you @orangewise for making this tool really really awesome & adding many features , Way to go !!!
