### ISSUE TITLE
0.4.1 not working

### ISSUE THREAD

**Issue by ssvaidyanathan** [anil614sagar/openapi2apigee#22]
@anil614sagar  - I installed the latest package (0.4.1)

The generateApi option creates the proxy folder on the defined directory but does not deploy

Can you please take a look - after getting all the info, it just exits

_ITs-MacBook-Pro-94: saisaranvaidyanathan$ openapi2apigee generateApi petStore -s http://petstore.swagger.io/v2/swagger.json -D -d ~/Desktop/
API name: Swagger Petstore, Version: 1.0.0
Apigee API bundle generated in location /Users/saisaranvaidyanathan/Desktop/
Initiating Apigee Deployment..
? Base URI? https://api.enterprise.apigee.com
? Organization? saisarantest
? User Id? ssvaidyanathan@apigee.com
? Password? *************
? Environment? test
? Virtual Hosts? default,secure
ITs-MacBook-Pro-94: saisaranvaidyanathan$_

Also - the URL of the petstore json is not correct, it should be http://petstore.swagger.io/v2/swagger.json not http://petstore.openapi.io/v2/openapi.json. Can you please update the docs

**Comment by anil614sagar** [comment]
@ssvaidyanathan  , Above issues has been fixed in 0.4.4 . Please re-install & let us know if any. Thank you for highlighting same.
