### ISSUE TITLE
Ability to specify the command line options within the command itself

### ISSUE THREAD

**Issue by jonesr91** [anil614sagar/openapi2apigee#29]
Is it possible to specify the command options (Base URI | Organization | User Id | Password | Environments | Virtual Hosts) within the command itself?

I'd like to run an automated script to deploy to a test environment, which doesn't require any user input. 

For example:
openapi2apigee generateApi myTestAPI --source mySwagger.json --deploy --baseuri https://api.enterprise.apigee.com --organization test --username test@test.com --password test --environments test --virtualhosts default

**Comment by jonesr91** [comment]
Apologies, I figured this out.

The example given above does work - I had been trying various different commands and the above one hadn't been tested prior to submitting this ticket.

**Comment by anil614sagar** [comment]
@jonesr91  , Yes, It does support , See the file [here](https://github.com/anil614sagar/openapi2apigee/blob/master/bin/openapi2apigee)

**Comment by anil614sagar** [comment]
@jonesr91 , No Issues, Glad you found it, You beat my answer by few seconds :)
