### ISSUE TITLE
<BasePath> of the Apigee proxy should be picked up from the spec

### ISSUE THREAD

**Issue by sudheesreedhara** [anil614sagar/openapi2apigee#36]
<HTTPProxyConnection>
        <BasePath>/{should_be_picked_up_from_the_spec}</BasePath>
        <Properties/>
        <VirtualHost>default</VirtualHost>
        <VirtualHost>secure</VirtualHost>
    </HTTPProxyConnection>

Currently this value is being set to API proxy name that is provided in the "generateApi" command.

**Comment by ssvaidyanathan** [comment]
Works with v0.6.2
