### ISSUE TITLE
Option to choose API Proxy Base Path 

### ISSUE THREAD

**Issue by anil614sagar** [anil614sagar/openapi2apigee#7]
When I deploy with swagger2api, the proxy name I choose also becomes the proxy endpoint basepath (which is not what I want). I have to go into the proxy endpoint and change the basepath from /<proxyname> to /v1.

Is there any way to set the proxy's basePath in Swagger, rather than having to edit it manually? If not, could it be added to swagger2api as an option?

**Comment by maruti123** [comment]
This is the same issue I am seeing and it would be good to get it fixed or enhanced.

**Comment by ssvaidyanathan** [comment]
Fixed in v0.9.0
